/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lukasz.skold;

import java.awt.Toolkit;


/**
 *
 * @author Lukasz Skold
 */
public class CurrencyCalculator extends javax.swing.JFrame {

    public DocumentParser docParser;
    
    /**
     * Creates new form CurrencyCalculator
     */
    public CurrencyCalculator() {
        initComponents();
        String fileURL = "xml/prices.xml";
        //Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/icons8_exchange_euro_70px.png"))
        docParser = new DocumentParser(fileURL);
        
        //System.out.print(docParser.arrayOfValues);
        wantedCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(docParser.arrayOfNames.toArray(new String[0])));
        wantedCurrency.setSelectedIndex(1);
        currentCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(docParser.arrayOfNames.toArray(new String[0])));
        currentCurrency.setSelectedIndex(0);
        
    }

    /**
     * 
     * @param string the string we are checking
     * @return true - if string is a number / otherwise false
     */
    private boolean isANumber(String string){
        
        if (string == null) {
            return false;
        }
        try {
            double d = Double.parseDouble(string);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    public void enterPressed(){
        
        String caughtText = input.getText();
        caughtText = caughtText.replace(',', '.');
        
         if(isANumber(caughtText)){
            double value = Double.parseDouble(caughtText);
            int wanted=0;
            int current=0;
            
            for(int i=0; i<docParser.arrayOfValues.size();i++){
                if(i == wantedCurrency.getSelectedIndex()){
                    wanted = i;

                }
            }  
            for(int i=0; i<docParser.arrayOfValues.size();i++){
                if(i == currentCurrency.getSelectedIndex()){
                    current = i;
                }
            }
            //System.out.println(current);      
            //System.out.println(wanted);
            double outValue = value*docParser.arrayOfValues.get(wanted)/docParser.arrayOfValues.get(current);
            //System.out.println(outValue);                  
            String outValueS = String.format("%.2f", outValue);
            outValueS = outValueS.replace(',', '.');
            System.out.println(outValueS);      
            output.setText(outValueS);
            
        }
    }
    
    
    
    /**
     *  SETTERS
     */
    public void setInputText(String str){
        input.setText(str);
    }
    public void setCurrentCurrencyIndex(int i){
        currentCurrency.setSelectedIndex(i);
    }
    public void setWantedCurrencyIndex(int i){
        wantedCurrency.setSelectedIndex(i);
    }
    
    /**
     *  GETTERS
     */
    public int getCurrentCurrencyIndex(){
       return currentCurrency.getSelectedIndex();
    }
    public int getWantedCurrencyIndex(){
       return wantedCurrency.getSelectedIndex();
    }
    public String getInputText(){
       return input.getText();
    }
    public String getOutputText(){
       return output.getText();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        output = new javax.swing.JTextField();
        currentCurrency = new javax.swing.JComboBox<>();
        wantedCurrency = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/icons8_exchange_euro_70px.png")));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(500, 300));

        leftPanel.setBackground(new java.awt.Color(0, 0, 153));
        leftPanel.setMinimumSize(new java.awt.Dimension(250, 350));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency");
        jLabel1.setIconTextGap(0);
        leftPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 255, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculator");
        jLabel2.setIconTextGap(0);
        leftPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 255, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lukasz/skold/images/icons8_cash_100px_1.png"))); // NOI18N
        leftPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 255, 145));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lukasz/skold/images/bg.png"))); // NOI18N
        leftPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 350));

        rightPanel.setBackground(new java.awt.Color(0, 102, 204));
        rightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        input.setText("Enter amount");
        input.setToolTipText("");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        rightPanel.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, 91, 34));

        output.setEditable(false);
        output.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });
        rightPanel.add(output, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 148, 91, 34));

        currentCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR" }));
        currentCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentCurrencyActionPerformed(evt);
            }
        });
        rightPanel.add(currentCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 73, 91, 33));
        currentCurrency.getAccessibleContext().setAccessibleDescription("");

        wantedCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wantedCurrencyActionPerformed(evt);
            }
        });
        rightPanel.add(wantedCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 148, 91, 33));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Your amount:");
        rightPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 51, 91, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Output:");
        rightPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 125, 91, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your currency:");
        rightPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 51, 91, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Wanted currency:");
        rightPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 125, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Made by");
        rightPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lukasz Skold");
        rightPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lukasz/skold/images/bg1.png"))); // NOI18N
        rightPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 350));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        rightPanel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentCurrencyActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void wantedCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wantedCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wantedCurrencyActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        enterPressed();
    }//GEN-LAST:event_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CurrencyCalculator().setVisible(true);
                CurrencyCalculator CC = new CurrencyCalculator();
                CC.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JComboBox<String> currentCurrency;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField output;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JComboBox<String> wantedCurrency;
    // End of variables declaration//GEN-END:variables
}
